# Generated by Django 3.2.8 on 2022-03-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_patient_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='path',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
