# Generated by Django 3.2.8 on 2022-03-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220315_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
