# Generated by Django 3.2.8 on 2022-03-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_document_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc',
        ),
    ]
