# Generated by Django 3.2.8 on 2022-03-15 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_document_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='path',
            new_name='name',
        ),
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
