# Generated by Django 3.2.8 on 2022-03-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220315_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
