# Generated by Django 3.2.8 on 2022-03-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220315_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(blank=True, to='main.Doctor'),
        ),
    ]
