# Generated by Django 3.2.8 on 2022-03-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='private',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='public',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
