# Generated by Django 4.0.3 on 2022-03-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220319_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='special',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
