# Generated by Django 4.0.3 on 2022-03-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_doctor_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Nonbinary')], default='Please choose your gender', max_length=1),
        ),
    ]
