# Generated by Django 4.0.3 on 2022-03-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='file',
            new_name='prescription',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='private',
            new_name='recipientPublic',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='public',
            new_name='senderPrivate',
        ),
        migrations.AddField(
            model_name='prescription',
            name='senderPublic',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
