# Generated by Django 4.0.3 on 2022-03-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_file_prescription_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
