# Generated by Django 4.0.3 on 2022-03-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_prescription_redeemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Nonbinary'), ('O', 'Other')], default='Please choose your gender', max_length=1),
        ),
    ]
