# Generated by Django 4.0.3 on 2022-03-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='job',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='special',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
