# Generated by Django 4.0.3 on 2022-03-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_doctor_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='degree',
        ),
    ]
