# Generated by Django 4.0.3 on 2022-03-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_doctor_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='job',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='special',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
