# Generated by Django 4.0.3 on 2022-03-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_document_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
    ]
